version: "3.9"

services:
  start:
    container_name: start
    build:
      context: ./
      dockerfile: start.Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    env_file:
    - .env